USE voice_input;

-- Hotword seed data sampled on 2026-05-24 from public hot lists:
-- Baidu: https://top.baidu.com/api/board?tab=realtime
-- Toutiao: https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc
-- Tencent News: https://r.inews.qq.com/gw/event/hot_ranking_list?page_size=50
--
-- The hotword table bootstrap targets user_id = 1. Change this variable before
-- running the script if another user should receive the default hotword group.
SET @hotword_bootstrap_user_id := 1;
SET @hotword_group_name := '通用';

INSERT INTO `hotword_seed` (`word`, `group_name`, `source`, `score`, `created_at`, `updated_at`)
VALUES
    ('神舟二十三号', @hotword_group_name, 'baidu', 100000, NOW(6), NOW(6)),
    ('航天员乘组', @hotword_group_name, 'baidu', 99000, NOW(6), NOW(6)),
    ('武契奇', @hotword_group_name, 'baidu', 98000, NOW(6), NOW(6)),
    ('长城', @hotword_group_name, 'baidu', 97000, NOW(6), NOW(6)),
    ('暴雨黄色预警', @hotword_group_name, 'baidu', 96000, NOW(6), NOW(6)),
    ('强对流天气', @hotword_group_name, 'baidu', 95000, NOW(6), NOW(6)),
    ('油车销量', @hotword_group_name, 'baidu', 94000, NOW(6), NOW(6)),
    ('新能源汽车', @hotword_group_name, 'baidu', 93000, NOW(6), NOW(6)),
    ('微信登录', @hotword_group_name, 'baidu', 92000, NOW(6), NOW(6)),
    ('山西煤矿事故', @hotword_group_name, 'baidu', 91000, NOW(6), NOW(6)),
    ('隐藏巷道', @hotword_group_name, 'baidu', 90000, NOW(6), NOW(6)),
    ('高铁行李架', @hotword_group_name, 'baidu', 89000, NOW(6), NOW(6)),
    ('全球高温', @hotword_group_name, 'baidu', 88000, NOW(6), NOW(6)),
    ('印度高温', @hotword_group_name, 'baidu', 87000, NOW(6), NOW(6)),
    ('刷手机', @hotword_group_name, 'baidu', 86000, NOW(6), NOW(6)),
    ('录取率', @hotword_group_name, 'baidu', 85000, NOW(6), NOW(6)),
    ('朱杨柱', @hotword_group_name, 'baidu', 84000, NOW(6), NOW(6)),
    ('张志远', @hotword_group_name, 'baidu', 83000, NOW(6), NOW(6)),
    ('黎家盈', @hotword_group_name, 'baidu', 82000, NOW(6), NOW(6)),
    ('跑男', @hotword_group_name, 'baidu', 81000, NOW(6), NOW(6)),
    ('高铁安全带', @hotword_group_name, 'baidu', 80000, NOW(6), NOW(6)),
    ('控碳水', @hotword_group_name, 'baidu', 79000, NOW(6), NOW(6)),
    ('微塑料', @hotword_group_name, 'baidu', 78000, NOW(6), NOW(6)),
    ('SK海力士', @hotword_group_name, 'baidu', 77000, NOW(6), NOW(6)),
    ('闽超', @hotword_group_name, 'baidu', 76000, NOW(6), NOW(6)),
    ('证券人员炒股', @hotword_group_name, 'baidu', 75000, NOW(6), NOW(6)),
    ('烧烤学院', @hotword_group_name, 'baidu', 74000, NOW(6), NOW(6)),
    ('手擀面商标', @hotword_group_name, 'baidu', 73000, NOW(6), NOW(6)),
    ('重庆永川暴雨', @hotword_group_name, 'baidu', 72000, NOW(6), NOW(6)),
    ('榛树导弹', @hotword_group_name, 'baidu', 71000, NOW(6), NOW(6)),
    ('煤矿爆炸', @hotword_group_name, 'toutiao', 99000, NOW(6), NOW(6)),
    ('神舟飞船升级', @hotword_group_name, 'toutiao', 98000, NOW(6), NOW(6)),
    ('赖清德', @hotword_group_name, 'toutiao', 97000, NOW(6), NOW(6)),
    ('中巴塞国旗', @hotword_group_name, 'toutiao', 96000, NOW(6), NOW(6)),
    ('燃油车市场', @hotword_group_name, 'toutiao', 95000, NOW(6), NOW(6)),
    ('股市上涨逻辑', @hotword_group_name, 'toutiao', 94000, NOW(6), NOW(6)),
    ('蜱虫', @hotword_group_name, 'toutiao', 93000, NOW(6), NOW(6)),
    ('台湾夫妻', @hotword_group_name, 'toutiao', 92000, NOW(6), NOW(6)),
    ('阴阳图纸', @hotword_group_name, 'toutiao', 91000, NOW(6), NOW(6)),
    ('越南禁烟', @hotword_group_name, 'toutiao', 90000, NOW(6), NOW(6)),
    ('高血压饮食', @hotword_group_name, 'toutiao', 89000, NOW(6), NOW(6)),
    ('小麦抢收', @hotword_group_name, 'toutiao', 88000, NOW(6), NOW(6)),
    ('武汉弹性上放学', @hotword_group_name, 'toutiao', 87000, NOW(6), NOW(6)),
    ('女选手隐私照', @hotword_group_name, 'toutiao', 86000, NOW(6), NOW(6)),
    ('龙卷风', @hotword_group_name, 'toutiao', 85000, NOW(6), NOW(6)),
    ('杜江', @hotword_group_name, 'toutiao', 84000, NOW(6), NOW(6)),
    ('新疆顶碗舞', @hotword_group_name, 'toutiao', 83000, NOW(6), NOW(6)),
    ('巴基斯坦总理访华', @hotword_group_name, 'toutiao', 82000, NOW(6), NOW(6)),
    ('霍尔木兹海峡', @hotword_group_name, 'toutiao', 81000, NOW(6), NOW(6)),
    ('湖北抢烘', @hotword_group_name, 'toutiao', 80000, NOW(6), NOW(6)),
    ('中塞铁杆友谊', @hotword_group_name, 'qqnews', 98000, NOW(6), NOW(6)),
    ('U17国足', @hotword_group_name, 'qqnews', 97000, NOW(6), NOW(6)),
    ('海军战机', @hotword_group_name, 'qqnews', 96000, NOW(6), NOW(6)),
    ('中国航天员', @hotword_group_name, 'qqnews', 95000, NOW(6), NOW(6)),
    ('马英九基金会', @hotword_group_name, 'qqnews', 94000, NOW(6), NOW(6)),
    ('入汛强降雨', @hotword_group_name, 'qqnews', 93000, NOW(6), NOW(6)),
    ('水贝金饰', @hotword_group_name, 'qqnews', 92000, NOW(6), NOW(6)),
    ('美伊备忘录', @hotword_group_name, 'qqnews', 91000, NOW(6), NOW(6)),
    ('AI一人公司', @hotword_group_name, 'qqnews', 90000, NOW(6), NOW(6)),
    ('吴艳妮', @hotword_group_name, 'qqnews', 89000, NOW(6), NOW(6)),
    ('生菜寄生虫', @hotword_group_name, 'qqnews', 88000, NOW(6), NOW(6)),
    ('白宫枪击案', @hotword_group_name, 'qqnews', 87000, NOW(6), NOW(6)),
    ('欧洲车企', @hotword_group_name, 'qqnews', 86000, NOW(6), NOW(6)),
    ('东北超', @hotword_group_name, 'qqnews', 85000, NOW(6), NOW(6)),
    ('苏超', @hotword_group_name, 'qqnews', 84000, NOW(6), NOW(6)),
    ('莲花味精', @hotword_group_name, 'qqnews', 83000, NOW(6), NOW(6)),
    ('英伟达', @hotword_group_name, 'qqnews', 82000, NOW(6), NOW(6)),
    ('福州地铁', @hotword_group_name, 'qqnews', 81000, NOW(6), NOW(6)),
    ('潮汕老板', @hotword_group_name, 'qqnews', 80000, NOW(6), NOW(6)),
    ('塞尔维亚总统', @hotword_group_name, 'qqnews', 79000, NOW(6), NOW(6))
ON DUPLICATE KEY UPDATE
    `group_name` = VALUES(`group_name`),
    `score` = VALUES(`score`),
    `updated_at` = NOW(6);

INSERT IGNORE INTO `hotword` (`user_id`, `group_name`, `word`, `created_at`)
VALUES
    (@hotword_bootstrap_user_id, @hotword_group_name, '神舟二十三号', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '航天员乘组', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '武契奇', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '长城', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '暴雨黄色预警', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '强对流天气', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '油车销量', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '新能源汽车', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '微信登录', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '山西煤矿事故', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '隐藏巷道', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '高铁行李架', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '全球高温', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '印度高温', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '刷手机', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '录取率', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '朱杨柱', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '张志远', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '黎家盈', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '跑男', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '高铁安全带', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '控碳水', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '微塑料', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, 'SK海力士', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '闽超', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '证券人员炒股', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '烧烤学院', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '手擀面商标', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '重庆永川暴雨', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '榛树导弹', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '煤矿爆炸', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '神舟飞船升级', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '赖清德', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '中巴塞国旗', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '燃油车市场', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '股市上涨逻辑', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '蜱虫', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '台湾夫妻', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '阴阳图纸', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '越南禁烟', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '高血压饮食', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '小麦抢收', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '武汉弹性上放学', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '女选手隐私照', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '龙卷风', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '杜江', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '新疆顶碗舞', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '巴基斯坦总理访华', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '霍尔木兹海峡', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '湖北抢烘', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '中塞铁杆友谊', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, 'U17国足', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '海军战机', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '中国航天员', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '马英九基金会', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '入汛强降雨', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '水贝金饰', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '美伊备忘录', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, 'AI一人公司', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '吴艳妮', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '生菜寄生虫', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '白宫枪击案', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '欧洲车企', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '东北超', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '苏超', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '莲花味精', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '英伟达', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '福州地铁', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '潮汕老板', NOW(6)),
    (@hotword_bootstrap_user_id, @hotword_group_name, '塞尔维亚总统', NOW(6));
